---
- name: Setup and Execute Python Script
  hosts: localhost
  gather_facts: no
  vars:
    # Specify the temporary directory here or pass via --extra-vars at runtime
    temp_dir: "{{ playbook_dir }}/ansible_playbooks"

  tasks:
    - name: Ensure Python 'requests' library is installed
      ansible.builtin.pip:
        name: requests
        state: present

    - name: Ensure temporary directory exists
      file:
        path: "{{ temp_dir }}"
        state: directory
        mode: '0755'

    - name: Download Python script from GitHub
      get_url:
        url: https://raw.githubusercontent.com/avinash-sha/test/main/scripts/get_security_patches.py
        dest: "{{ playbook_dir }}/get_security_patches.py"
        mode: '0755'
        validate_certs: no

    - name: Execute Python script to generate playbooks
      command: python3 "{{ playbook_dir }}/get_security_patches.py" "{{ temp_dir }}"
      register: script_output
      failed_when: script_output.rc != 0

    - name: Clean up downloaded Python script
      file:
        path: "{{ playbook_dir }}/get_security_patches.py"
        state: absent

- name: Deploy and Execute Playbooks on Hosts
  hosts: all
  gather_facts: yes
  vars:
    temp_dir: "{{ playbook_dir }}/ansible_playbooks"

  tasks:
    - name: Execute the playbook
      ansible.builtin.command:
        cmd: ansible-playbook "{{ temp_dir }}/{{ ansible_distribution|lower }}_playbook.yml"
      when: ansible_distribution in ['Ubuntu', 'Fedora', 'Rocky', 'RedHat']

    - name: Clean up playbook on remote host
      file:
        path: "{{ temp_dir }}/{{ ansible_distribution|lower }}_playbook.yml"
        state: absent
      when: ansible_distribution in ['Ubuntu', 'Fedora', 'Rocky', 'RedHat']
