---
- name: Update the package cache
  apt:
    update_cache: yes
    force_apt_get: yes
  register: cache_updated

- name: Upgrade all packages to the latest version
  apt:
    upgrade: dist
    force_apt_get: yes
  register: packages_upgraded

- name: Remove unnecessary packages
  apt:
    autoremove: yes
    force_apt_get: yes

- name: Clean up the package cache
  apt:
    autoclean: yes
    force_apt_get: yes

- name: Check if reboot is needed
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot the machine if required
  reboot:
    reboot_timeout: 600
  when: reboot_required.stat.exists

- name: Save update report
  copy:
    content: "{{ packages_upgraded }}"
    dest: "/var/log/apt_update_info_{{ ansible_date_time.iso8601 }}.log"
