---
- name: Refresh all repositories
  zypper:
    update_cache: yes

- name: Upgrade all packages
  zypper:
    name: "*"
    state: latest
  register: packages_upgraded

- name: Remove unneeded packages
  zypper:
    name: "{{ item }}"
    state: absent
  with_items: "{{ packages_upgraded.results | selectattr('state', 'equalto', 'removed') | map(attribute='name') | list }}"
  when: packages_upgraded is changed

- name: Check if reboot is needed
  shell: 'zypper ps -s'
  ignore_errors: true
  register: reboot_needed

- name: Reboot the machine if required
  reboot:
    reboot_timeout: 600
  when: "'No processes using deleted files found.' not in reboot_needed.stdout"

- name: Save update report
  copy:
    content: "{{ packages_upgraded }}"
    dest: "/var/log/zypper_update_info_{{ ansible_date_time.iso8601 }}.log"
